<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnableMSTestRunner>true</EnableMSTestRunner>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
		<PackageReference Include="ExcelToEnumerable" Version="0.3.10" />
		<PackageReference Include="Keycloak.AuthServices.Sdk.Kiota" Version="26.5.6" />
		<PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="10.0.9" />
		<PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.7.1" />
		<PackageReference Include="Microsoft.CodeCoverage" Version="18.7.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
		<PackageReference Include="MockQueryable.NSubstitute" Version="10.0.8" />
		<PackageReference Include="coverlet.collector" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NSubstitute" Version="6.0.0" />
		<PackageReference Include="Riok.Mapperly" Version="4.3.1" />
		<PackageReference Include="SkiaSharp" Version="4.150.0" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.3" />
		<PackageReference Include="TUnit" Version="1.59.0" />
		<PackageReference Include="Verify.DiffPlex" Version="3.3.0" />
		<PackageReference Include="Verify.TUnit" Version="31.24.1" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Snapshots\Test1.TestMethod1\" />
	</ItemGroup>

</Project>
